### ISSUE TITLE
http unsupported (self hosting)

### ISSUE THREAD

**Issue by kylewill** [typesense/firestore-typesense-search#4]
Testing with self hosted instance and entered `[IP ADDRESS]:8108` in the Extension configuration. 

Firebase Functions logs show the port is updated to 443 and the connection is refused:

![image](https://user-images.githubusercontent.com/3108182/123863025-0c4fa500-d8f7-11eb-8860-7a3b9fb7a811.png)

**Comment by jasonbosco** [comment]
Ah yes, I didn't want to have one too many configuration options when setting up the extension. Would it be possible for you to use port 443? 

Figured since API calls are made over public networks, it's a good idea to use https/443 when running your Typesense cluster. 

You'd just need to get an SSL certificate and pass the location to the Typesense process when starting it up. See SSL params here: https://typesense.org/docs/0.19.0/guide/configure-typesense.html

**Comment by kylewill** [comment]
Makes sense :) I can (and have now!) it was an unexpected speedbump switching from the docs to the extension but not too hard to get working. Thank you!
